# Generated by Django 5.2.6 on 2025-09-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idwtf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, help_text='Tags this profile follows (tags are owned by other profiles)', related_name='followed_by_profile', to='idwtf.tag'),
        ),
    ]
