# Generated by Django 6.0 on 2025-12-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idwtf', '0003_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='images/profiles_images'),
        ),
    ]
